name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build -t docker.pkg.github.com/zekth/go_qmk/go_qmk:latest .
      - name: Docker Build and publish latest
        if: github.ref == 'refs/heads/master' && github.repository == 'zekth/go_qmk'
        run: |
          docker login -u zekth -p ${{ secrets.DOCKER_TOKEN }} docker.pkg.github.com
          sh ./scripts/docker_publish.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'zekth/go_qmk'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
      # - name: Deploy the Docker image to GitHub Package Registry
      #   if: startsWith(github.ref, 'refs/tags/') && github.repository == 'zekth/go_qmk'
      #   uses: elgohr/Publish-Docker-Github-Action@master
      #   with:
      #     name: zekth/go_qmk
      #     dockerfile: Dockerfile
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     registry: docker.pkg.github.com
      #     tag_names: true
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy script
        run: |
          echo deploy
