name: Build
on: ['push','pull_request']
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.6
      - name: Test
        run: cd api && make test
      - name: Docker Build
        run: docker build -t go_qmk .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'zekth/go_qmk'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
      # - name: Deploy the Docker image to GitHub Package Registry
      #   if: startsWith(github.ref, 'refs/tags/') && github.repository == 'zekth/go_qmk'
      #   uses: elgohr/Publish-Docker-Github-Action@master
      #   with:
      #     name: zekth/go_qmk
      #     dockerfile: Dockerfile
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     registry: docker.pkg.github.com
      #     tag_names: true
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy script
        run: |
          echo deploy
